[theme]
base = "light"
primaryColor = "#4B7BEC"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f6fa"
textColor = "#2f3542"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
